<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <PackageId>YellowDogMan.Elements.Core</PackageId>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Data Types\HalfVectors.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HalfVectors.tt</DependentUpon>
    </Compile>
    <Compile Update="Data Types\SphericalHarmonics\SphericalHarmonics.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SphericalHarmonics.tt</DependentUpon>
    </Compile>
    <Compile Update="Extensions\MathXDivision.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>MathXDivision.tt</DependentUpon>
    </Compile>
    <Compile Update="CoderGen.cs">
      <DependentUpon>CoderGen.tt</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Collections\SlimListGen.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>SlimListGen.tt</DependentUpon>
    </Compile>
    <Compile Update="Colors\colorX.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>colorX.tt</DependentUpon>
    </Compile>
    <Compile Update="Data Types\Quaternions.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Quaternions.tt</DependentUpon>
    </Compile>
    <Compile Update="Data Types\VectorTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>VectorTypes.tt</DependentUpon>
    </Compile>
    <Compile Update="Encoding\DataTreeSerializer\Generic Interface\LoadSaveHelper.cs">
      <DependentUpon>LoadSaveHelper.tt</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Extensions\MathXGen.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>MathXGen.tt</DependentUpon>
    </Compile>
    <Compile Update="Extensions\RobustParser.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>RobustParser.tt</DependentUpon>
    </Compile>
    <Compile Update="Data Types\Color.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Color.tt</DependentUpon>
    </Compile>
    <Compile Update="Data Types\MatrixTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>MatrixTypes.tt</DependentUpon>
    </Compile>
    <Compile Update="Encoding\DataTreeSerializer\Generic Interface\DataTreeDictionaryQuickValues.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>DataTreeDictionaryQuickValues.tt</DependentUpon>
    </Compile>
    <Compile Update="Extensions\MathWrapper.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>MathWrapper.tt</DependentUpon>
    </Compile>
    <Compile Update="Utility\PrimitiveTryParsers.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>PrimitiveTryParsers.tt</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Extensions\MathXDivision.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>MathXDivision.cs</LastGenOutput>
    </Content>
    <Content Include="CoderGen.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>CoderGen.cs</LastGenOutput>
    </Content>
    <Content Include="Collections\SlimListGen.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>SlimListGen.cs</LastGenOutput>
    </Content>
    <Content Include="Colors\colorX.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>colorX.cs</LastGenOutput>
    </Content>
    <Content Include="Data Types\Color.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Color.cs</LastGenOutput>
    </Content>
    <Content Include="Data Types\MatrixTypes.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>MatrixTypes.cs</LastGenOutput>
    </Content>
    <Content Include="Data Types\Primitives.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
    </Content>
    <Content Include="Data Types\Quaternions.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Quaternions.cs</LastGenOutput>
    </Content>
    <Content Include="Data Types\VectorTypes.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>VectorTypes.cs</LastGenOutput>
    </Content>
    <Content Include="Encoding\DataTreeSerializer\Generic Interface\DataTreeDictionaryQuickValues.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>DataTreeDictionaryQuickValues.cs</LastGenOutput>
    </Content>
    <Content Include="Encoding\DataTreeSerializer\Generic Interface\DataTreeValueTypes.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
    </Content>
    <Content Include="Encoding\DataTreeSerializer\Generic Interface\LoadSaveHelper.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>LoadSaveHelper.cs</LastGenOutput>
    </Content>
    <Content Include="Extensions\MathWrapper.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>MathWrapper.cs</LastGenOutput>
    </Content>
    <Content Include="Extensions\MathXGen.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>MathXGen.cs</LastGenOutput>
    </Content>
    <Content Include="Extensions\RobustParser.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>RobustParser.cs</LastGenOutput>
    </Content>
    <Content Include="Utility\PrimitiveTryParsers.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>PrimitiveTryParsers.cs</LastGenOutput>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodeGenerationConfig\CodeGenerationConfig.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BrotliSharpLib" Version="0.3.3" />
    <PackageReference Include="C5" Version="3.0.0" />
    <PackageReference Include="Enums.NET" Version="5.0.0" />
    <PackageReference Include="LinqFaster" Version="1.0.0" />
    <PackageReference Include="LinqFaster.SIMD" Version="1.0.3" />
    <PackageReference Include="LinqFaster.SIMD.Parallel" Version="1.0.2" />
    <PackageReference Include="LZMA-SDK" Version="22.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3" />
    <PackageReference Include="Otp.NET" Version="1.4.1" />
    <PackageReference Include="YellowDogMan.Brotli.NET" Version="2.1.1-ydm-0.2.3" />
    <PackageReference Include="YellowDogMan.BepuPhysics" Version="2.4.0.2-ydm-0.1.7" />
    <PackageReference Include="YellowDogMan.Elements.Data" Version="1.0.0" />
    <PackageReference Include="YellowDogMan.Elements.Quantity" Version="0.3.0" />
    <PackageReference Include="YellowDogMan.LZ4" Version="1.0.10.93-ydm-0.1.3" />
    <PackageReference Include="YellowDogMan.MimeDetective" Version="0.3.0" />
    <PackageReference Include="YellowDogMan.Renderite.Shared" Version="1.2.0" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Data Types\HalfVectors.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HalfVectors.tt</DependentUpon>
    </None>
    <None Include="Data Types\SphericalHarmonics\SphericalHarmonics.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SphericalHarmonics.tt</DependentUpon>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Data Types\HalfVectors.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>HalfVectors.cs</LastGenOutput>
    </None>
    <None Update="Data Types\SphericalHarmonics\SphericalHarmonics.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>SphericalHarmonics.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <PropertyGroup />
</Project>
